export const routes = {
  forms: {
    profileSettings: "/forms/profile-settings",
    notificationPreference: "/forms/profile-settings/notification",
    personalInformation: "/forms/profile-settings/profile",
    newsletter: "/forms/newsletter",
  },
  emailTemplates: "/email-templates",
  profile: "/profile",
  welcome: "/welcome",
  comingSoon: "/coming-soon",
  accessDenied: "/access-denied",
  notFound: "/not-found",
  maintenance: "/maintenance",
  blank: "/blank",
  auth: {
    signUp1: "/auth/sign-up-1",
    signUp2: "/auth/sign-up-2",
    signUp3: "/auth/sign-up-3",
    signUp4: "/auth/sign-up-4",
    signUp5: "/auth/sign-up-5",
    // sign in
    signIn1: "/auth/sign-in-1",
    signIn2: "/auth/sign-in-2",
    signIn3: "/auth/sign-in-3",
    signIn4: "/auth/sign-in-4",
    signIn5: "/auth/sign-in-5",
    // forgot password
    forgotPassword1: "/auth/forgot-password-1",
    forgotPassword2: "/auth/forgot-password-2",
    forgotPassword3: "/auth/forgot-password-3",
    forgotPassword4: "/auth/forgot-password-4",
    forgotPassword5: "/auth/forgot-password-5",
    // OTP
    otp1: "/auth/otp-1",
    otp2: "/auth/otp-2",
    otp3: "/auth/otp-3",
    otp4: "/auth/otp-4",
    otp5: "/auth/otp-5",
  },
  signIn: "/giris",
  tektas: {
    dashboard: "/tektas",
    products: "/tektas/urunler",
  },
  trendyol: {
    dashboard: "/trendyol",
    orders: "/trendyol/siparisler",
    stockPrice: "/trendyol/stok-fiyat",
    products: "/trendyol/urunler",
    config: "/trendyol/yapilandirma",
  },
  sanalMagaza: {
    dashboard: "/sanal-magaza",
  },
  tanimlama: {
    markalar: "/tanimlama/markalar",
    createMarka: "/tanimlama/markalar/create",
    editMarka: (id: string) => `/tanimlama/markalar/${id}/edit`,
    urunMarkalar: "/tanimlama/urun-markalar",
    createUrunMarka: "/tanimlama/urun-markalar/create",
    editUrunMarka: (id: string) => `/tanimlama/urun-markalar/${id}/edit`,
  },
};
