import {
  // Genel & Navigasyon
  PiHouseLine,
  PiFolder,
  PiTable,
  PiList,
  PiGridFour,
  PiSquaresFour,
  PiSidebarSimple,
  PiCaretRight,
  PiCaretLeft,
  PiCaretDown,
  PiCaretUp,
  PiArrowRight,
  PiArrowLeft,
  PiArrowUp,
  PiArrowDown,
  PiArrowLeftBold,
  PiArrowsClockwise,
  PiMagnifyingGlass,
  PiX,
  PiPlus,
  PiMinus,
  PiDotsThreeVertical,
  PiDotsThree,
  
  // Kullanıcı & Hesap
  PiUserCircle,
  PiUsers,
  PiUserPlus,
  PiUserMinus,
  PiUserGear,
  PiUserCheck,
  PiUserList,
  PiUserFocus,
  PiIdentificationCard,
  PiAddressBook,
  
  // Ayarlar & Sistem
  PiGear,
  PiGearSix,
  PiSliders,
  PiToggleLeft,
  PiToggleRight,
  PiBell,
  PiBellRinging,
  PiShieldCheck,
  PiLock,
  PiLockOpen,
  PiKey,
  
  // E-ticaret & Finans
  PiShoppingCart,
  PiShoppingBag,
  PiStorefront,
  PiPackage,
  PiTruck,
  PiReceipt,
  PiInvoice,
  PiCreditCard,
  PiCurrencyDollar,
  PiCurrencyEur,
  PiCoin,
  PiWallet,
  PiTag,
  PiBarcode,
  PiQrCode,
  
  // Grafikler & Raporlar
  PiChartBar,
  PiChartLine,
  PiChartPie,
  PiChartLineUp,
  PiChartLineDown,
  PiChartBarHorizontal,
  PiPresentationChart,
  PiTrendUp,
  PiTrendDown,
  PiGraph,
  
  // Dosya & Döküman
  PiFileText,
  PiFile,
  PiFiles,
  PiFileDoc,
  PiFilePdf,
  PiFileXls,
  PiFileCsv,
  PiFileImage,
  PiFileVideo,
  PiFileZip,
  PiClipboardText,
  PiClipboard,
  PiNote,
  PiNotebook,
  PiArticle,
  PiFolderOpen,
  PiFolderPlus,
  
  // Düzenleme & İşlemler
  PiPencil,
  PiPencilSimple,
  PiTrash,
  PiCopy,
  PiDownload,
  PiUpload,
  PiFloppyDisk,
  PiPrinter,
  PiExport,
  PiShareNetwork,
  
  // İletişim
  PiEnvelope,
  PiEnvelopeSimple,
  PiPhone,
  PiPhoneCall,
  PiChat,
  PiChats,
  PiChatCircle,
  PiPaperPlane,
  PiWhatsappLogo,
  
  // Medya & Görsel
  PiImage,
  PiImages,
  PiCamera,
  PiVideo,
  PiVideoCamera,
  PiMusicNote,
  PiPlay,
  PiPause,
  PiStop,
  
  // Tarih & Zaman
  PiCalendar,
  PiCalendarBlank,
  PiCalendarCheck,
  PiClock,
  PiClockClockwise,
  PiTimer,
  PiHourglass,
  
  // Konum & Harita
  PiMapPin,
  PiMapPinLine,
  PiMapTrifold,
  PiGlobe,
  PiNavigationArrow,
  PiCompass,
  
  // Durum & Bildirim
  PiCheckCircle,
  PiXCircle,
  PiWarningCircle,
  PiInfo,
  PiQuestion,
  PiProhibit,
  PiSealCheck,
  PiSealWarning,
  
  // Görünüm
  PiEye,
  PiEyeSlash,
  PiEyeClosed,
  PiStar,
  PiStarFill,
  PiHeart,
  PiHeartFill,
  PiThumbsUp,
  PiThumbsDown,
  
  // Listeler & Organizasyon
  PiListChecks,
  PiListBullets,
  PiListNumbers,
  PiListDashes,
  PiKanban,
  PiBookmark,
  PiBookmarks,
  
  // Bağlantı & Network
  PiLink,
  PiLinkSimple,
  PiLinkBreak,
  PiGitBranch,
  PiGitCommit,
  PiDatabase,
  PiCloudArrowDown,
  PiCloudArrowUp,
  PiCloud,
  
  // Diğer
  PiFlag,
  PiLightbulb,
  PiTarget,
  PiRocket,
  PiSuitcase,
  PiBuilding,
  PiBriefcase,
  PiCertificate,
  PiMedal,
  PiTrophy,
  
} from 'react-icons/pi';

// İkon eşleştirme map'i
export const iconMap: Record<string, React.ReactElement> = {
  // Genel & Navigasyon
  PiHouseLine: <PiHouseLine />,
  PiFolder: <PiFolder />,
  PiTable: <PiTable />,
  PiList: <PiList />,
  PiGridFour: <PiGridFour />,
  PiSquaresFour: <PiSquaresFour />,
  PiSidebarSimple: <PiSidebarSimple />,
  PiCaretRight: <PiCaretRight />,
  PiCaretLeft: <PiCaretLeft />,
  PiCaretDown: <PiCaretDown />,
  PiCaretUp: <PiCaretUp />,
  PiArrowRight: <PiArrowRight />,
  PiArrowLeft: <PiArrowLeft />,
  PiArrowUp: <PiArrowUp />,
  PiArrowDown: <PiArrowDown />,
  PiArrowLeftBold: <PiArrowLeftBold />,
  PiArrowsClockwise: <PiArrowsClockwise />,
  PiMagnifyingGlass: <PiMagnifyingGlass />,
  PiX: <PiX />,
  PiPlus: <PiPlus />,
  PiMinus: <PiMinus />,
  PiDotsThreeVertical: <PiDotsThreeVertical />,
  PiDotsThree: <PiDotsThree />,
  
  // Kullanıcı & Hesap
  PiUserCircle: <PiUserCircle />,
  PiUsers: <PiUsers />,
  PiUserPlus: <PiUserPlus />,
  PiUserMinus: <PiUserMinus />,
  PiUserGear: <PiUserGear />,
  PiUserCheck: <PiUserCheck />,
  PiUserList: <PiUserList />,
  PiUserFocus: <PiUserFocus />,
  PiIdentificationCard: <PiIdentificationCard />,
  PiAddressBook: <PiAddressBook />,
  
  // Ayarlar & Sistem
  PiGear: <PiGear />,
  PiGearSix: <PiGearSix />,
  PiSliders: <PiSliders />,
  PiToggleLeft: <PiToggleLeft />,
  PiToggleRight: <PiToggleRight />,
  PiBell: <PiBell />,
  PiBellRinging: <PiBellRinging />,
  PiShieldCheck: <PiShieldCheck />,
  PiLock: <PiLock />,
  PiLockOpen: <PiLockOpen />,
  PiKey: <PiKey />,
  
  // E-ticaret & Finans
  PiShoppingCart: <PiShoppingCart />,
  PiShoppingBag: <PiShoppingBag />,
  PiStorefront: <PiStorefront />,
  PiPackage: <PiPackage />,
  PiTruck: <PiTruck />,
  PiReceipt: <PiReceipt />,
  PiInvoice: <PiInvoice />,
  PiCreditCard: <PiCreditCard />,
  PiCurrencyDollar: <PiCurrencyDollar />,
  PiCurrencyEur: <PiCurrencyEur />,
  PiCoin: <PiCoin />,
  PiWallet: <PiWallet />,
  PiTag: <PiTag />,
  PiBarcode: <PiBarcode />,
  PiQrCode: <PiQrCode />,
  
  // Grafikler & Raporlar
  PiChartBar: <PiChartBar />,
  PiChartLine: <PiChartLine />,
  PiChartPie: <PiChartPie />,
  PiChartLineUp: <PiChartLineUp />,
  PiChartLineDown: <PiChartLineDown />,
  PiChartBarHorizontal: <PiChartBarHorizontal />,
  PiPresentationChart: <PiPresentationChart />,
  PiTrendUp: <PiTrendUp />,
  PiTrendDown: <PiTrendDown />,
  PiGraph: <PiGraph />,
  
  // Dosya & Döküman
  PiFileText: <PiFileText />,
  PiFile: <PiFile />,
  PiFiles: <PiFiles />,
  PiFileDoc: <PiFileDoc />,
  PiFilePdf: <PiFilePdf />,
  PiFileXls: <PiFileXls />,
  PiFileCsv: <PiFileCsv />,
  PiFileImage: <PiFileImage />,
  PiFileVideo: <PiFileVideo />,
  PiFileZip: <PiFileZip />,
  PiClipboardText: <PiClipboardText />,
  PiClipboard: <PiClipboard />,
  PiNote: <PiNote />,
  PiNotebook: <PiNotebook />,
  PiArticle: <PiArticle />,
  PiFolderOpen: <PiFolderOpen />,
  PiFolderPlus: <PiFolderPlus />,
  
  // Düzenleme & İşlemler
  PiPencil: <PiPencil />,
  PiPencilSimple: <PiPencilSimple />,
  PiTrash: <PiTrash />,
  PiCopy: <PiCopy />,
  PiDownload: <PiDownload />,
  PiUpload: <PiUpload />,
  PiFloppyDisk: <PiFloppyDisk />,
  PiPrinter: <PiPrinter />,
  PiExport: <PiExport />,
  PiShareNetwork: <PiShareNetwork />,
  
  // İletişim
  PiEnvelope: <PiEnvelope />,
  PiEnvelopeSimple: <PiEnvelopeSimple />,
  PiPhone: <PiPhone />,
  PiPhoneCall: <PiPhoneCall />,
  PiChat: <PiChat />,
  PiChats: <PiChats />,
  PiChatCircle: <PiChatCircle />,
  PiPaperPlane: <PiPaperPlane />,
  PiWhatsappLogo: <PiWhatsappLogo />,
  
  // Medya & Görsel
  PiImage: <PiImage />,
  PiImages: <PiImages />,
  PiCamera: <PiCamera />,
  PiVideo: <PiVideo />,
  PiVideoCamera: <PiVideoCamera />,
  PiMusicNote: <PiMusicNote />,
  PiPlay: <PiPlay />,
  PiPause: <PiPause />,
  PiStop: <PiStop />,
  
  // Tarih & Zaman
  PiCalendar: <PiCalendar />,
  PiCalendarBlank: <PiCalendarBlank />,
  PiCalendarCheck: <PiCalendarCheck />,
  PiClock: <PiClock />,
  PiClockClockwise: <PiClockClockwise />,
  PiTimer: <PiTimer />,
  PiHourglass: <PiHourglass />,
  
  // Konum & Harita
  PiMapPin: <PiMapPin />,
  PiMapPinLine: <PiMapPinLine />,
  PiMapTrifold: <PiMapTrifold />,
  PiGlobe: <PiGlobe />,
  PiNavigationArrow: <PiNavigationArrow />,
  PiCompass: <PiCompass />,
  
  // Durum & Bildirim
  PiCheckCircle: <PiCheckCircle />,
  PiXCircle: <PiXCircle />,
  PiWarningCircle: <PiWarningCircle />,
  PiInfo: <PiInfo />,
  PiQuestion: <PiQuestion />,
  PiProhibit: <PiProhibit />,
  PiSealCheck: <PiSealCheck />,
  PiSealWarning: <PiSealWarning />,
  
  // Görünüm
  PiEye: <PiEye />,
  PiEyeSlash: <PiEyeSlash />,
  PiEyeClosed: <PiEyeClosed />,
  PiStar: <PiStar />,
  PiStarFill: <PiStarFill />,
  PiHeart: <PiHeart />,
  PiHeartFill: <PiHeartFill />,
  PiThumbsUp: <PiThumbsUp />,
  PiThumbsDown: <PiThumbsDown />,
  
  // Listeler & Organizasyon
  PiListChecks: <PiListChecks />,
  PiListBullets: <PiListBullets />,
  PiListNumbers: <PiListNumbers />,
  PiListDashes: <PiListDashes />,
  PiKanban: <PiKanban />,
  PiBookmark: <PiBookmark />,
  PiBookmarks: <PiBookmarks />,
  
  // Bağlantı & Network
  PiLink: <PiLink />,
  PiLinkSimple: <PiLinkSimple />,
  PiLinkBreak: <PiLinkBreak />,
  PiGitBranch: <PiGitBranch />,
  PiGitCommit: <PiGitCommit />,
  PiDatabase: <PiDatabase />,
  PiCloudArrowDown: <PiCloudArrowDown />,
  PiCloudArrowUp: <PiCloudArrowUp />,
  PiCloud: <PiCloud />,
  
  // Diğer
  PiFlag: <PiFlag />,
  PiLightbulb: <PiLightbulb />,
  PiTarget: <PiTarget />,
  PiRocket: <PiRocket />,
  PiSuitcase: <PiSuitcase />,
  PiBuilding: <PiBuilding />,
  PiBriefcase: <PiBriefcase />,
  PiCertificate: <PiCertificate />,
  PiMedal: <PiMedal />,
  PiTrophy: <PiTrophy />,
};

// Varsayılan ikon
export const defaultIcon = <PiFolder />;

// İkon adından ikon elementi döndür
export function getIconByName(iconName?: string): React.ReactElement | undefined {
  if (!iconName) return undefined;
  return iconMap[iconName] || undefined;
}


